name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd guitar-learning
          yarn install

      - name: Build Next.js
        run: |
          cd guitar-learning
          next build

      - name: Move Next.js files to root (for GitHub Pages)
        run: |
          mv guitar-learning/out/_next ./_next  # Moves _next to the correct directory

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_next # Upload the _next folder to be used in deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: ./ # Deploy from root directory (containing _next/ and the built files)
