name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies using npm
        run: |
          cd guitar-learning  # Change to the guitar-learning directory
          npm install  # Install dependencies using npm

      - name: Build Next.js app
        run: |
          cd guitar-learning  # Change to guitar-learning directory
          npx next build  # Build the Next.js app using npx (ensures Next.js is used from local node_modules)

      - name: Export static files
        run: |
          cd guitar-learning  # Change to guitar-learning directory
          npx next export  # Export static files to /out

      - name: Move build files to root directory
        run: |
          mv guitar-learning/out/* ./  # Move all files from guitar-learning/out to root directory
          mv guitar-learning/_next ./_next  # Move the _next folder to root

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Upload everything from the root directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: ./  # Deploy everything from the root directory
